#!/bin/bash

################################################################################
#      This file is part of LibreELEC - https://libreelec.tv
#      Copyright (C) 2017-present Team LibreELEC
#
#  LibreELEC is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 2 of the License, or
#  (at your option) any later version.
#
#  LibreELEC is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with LibreELEC.  If not, see <http://www.gnu.org/licenses/>.
################################################################################

. config/options $1

if [ -z "$PKG_INSTALL_VERSION" ]; then
  echo "ERROR: PKG_INSTALL_VERSION must be defined in the Python package!"
  exit 1
fi

printf "%${BUILD_INDENT}c $(print_color CLR_FIXPYTHON "SWITCHPYTHON")   $1 ($PKG_INSTALL_VERSION)\n" ' '>&$SILENT_OUT

rm -f $TOOLCHAIN/bin/python $SYSROOT_PREFIX/usr/bin/python $SYSROOT_PREFIX/usr/bin/python-config

[ -f $TOOLCHAIN/bin/$PKG_INSTALL_VERSION ] && ln -sf ${PKG_INSTALL_VERSION} $TOOLCHAIN/bin/python

[ -f $SYSROOT_PREFIX/usr/bin/${PKG_INSTALL_VERSION} ] && ln -sf ${PKG_INSTALL_VERSION} $SYSROOT_PREFIX/usr/bin/python
[ -f $SYSROOT_PREFIX/usr/bin/${PKG_INSTALL_VERSION}-config ] && ln -sf ${PKG_INSTALL_VERSION}-config $SYSROOT_PREFIX/usr/bin/python-config

[ -d $TOOLCHAIN/bin ] && echo "$1" >$TOOLCHAIN/bin/.installed.python

exit 0
